music.setVolume(90)
music.setTempo(112)
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Half))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Eighth))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Half))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Whole))
